### ISSUE TITLE
Incomplete Readme : learning and contributing

### ISSUE THREAD

**Issue by G8XSU** [IITH/alumni-portal#14]
Add starting Django app and contributing in readme. 
add a list of small todo's in readme .

**Comment by chirag200666** [comment]
@G8XSU 
* starting the Django app has been mentioned in the Readme.
* Describing contribution to a github project is a different topic in itself, it cannot be part of readme but to get people started it should be added somewhere. I will gather resources around how to get started and add in the project itself.
* List of Todo's : yes we need that, the objectives and overview were added by @rushiagr  here https://github.com/IITH/alumni-portal/issues/2 and initial set of tasks here https://github.com/IITH/alumni-portal/issues/10. I think we can further divide the objectives into actionable goals and smaller tasks, making it easier for people to get started with. I would like to add @ajayaa  and @rushiagr into the discussion.

**Comment by ajayaa** [comment]
@chirag200666 @G8XSU 

We will track feature development through issues only. It won't be a part of readme. There are tons of features to be developed. We are very happy to have people contributing. Chirag has described few features which are essential to the site now. You can go through those and let us know if you find something interesting. As we see more contributors we would have documents describing features in detail.

Also go through some external sites to learn about django. for e.g.
http://www.tangowithdjango.com/

If there are enough number of people interested in learning git workflow then we can have a short hangout session. If you know it already then that's awesome.

**Comment by rushiagr** [comment]
@ajayaa +1

Idea: how about creating a repo in iith organization, where we keep links of all the useful articles/getting started guides/tutorials for specific subjects related to programming/softwares, in our case starting with Django?

**Comment by ajayaa** [comment]
I think it's a good idea, if people really need it and use it.
